# Configuración para air

root = "."
tmp_dir = "tmp"

# Comando para ejecutar la aplicación
[build]
  cmd = "go build -o /usr/local/bin/app ./cmd/main.go"
  bin = "/usr/local/bin/app"
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "DB"]

# Opciones para el entorno de desarrollo
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"